### ISSUE TITLE
Musicbrainz_acoustid.user.js: No IDs when viewing a specific track in a release 

### ISSUE THREAD

**Issue by HenryGessau** [otringal/MB-userscripts#8]
When I view a release, the Acoustids show up fine, for example:
https://musicbrainz.org/release/5708a868-558b-4a8a-9593-558a638e1993
![image](https://github.com/user-attachments/assets/44aee02f-94d1-4cd4-a8d8-1c19102afca7)

However, when I view a specific track in a release, the Acoustids are missing, for example:
https://musicbrainz.org/release/5708a868-558b-4a8a-9593-558a638e1993/disc/1#7f6ceb63-756c-4486-9ff9-4f76bf2e1da6
![image](https://github.com/user-attachments/assets/918b0124-f1f5-4e03-9cec-69199104b09b)

I tried adding @match criteria, but neither of these seem to work:
```
// @match         *://*.musicbrainz.org/release/*/disc/*
// @match         *://*.musicbrainz.org/release/*/disc/*#*
```

**Comment by otringal** [comment]
Hi, thanks for reporting this. I never use the track page myself so I would never have noticed this. It took a quick look and it appears that it's actually the regex on line 204 that needs to be updated. I'll try to fix this later this weekend.

**Comment by HenryGessau** [comment]
Thanks! Works great!
